PR-checker - edge-testnet - add custom domain check
This will fail however as of now.

```
pe-utils$ fw-tools/edge-testnet --domain pdm-sandbox.io
[ FAILED ]	ping bootstrappdm-sandbox.io
[ FAILED ]	ping tcp-bootstrappdm-sandbox.io
[ FAILED ]	ping lwm2mpdm-sandbox.io
[ FAILED ]	ping tcp-lwm2mpdm-sandbox.io
[ FAILED ]	netcat bootstrappdm-sandbox.io 5684
[ FAILED ]	netcat tcp-bootstrappdm-sandbox.io 5684
[ FAILED ]	netcat bootstrappdm-sandbox.io 443
[ FAILED ]	netcat tcp-bootstrappdm-sandbox.io 443
[ FAILED ]	netcat lwm2mpdm-sandbox.io 5684
[ FAILED ]	netcat tcp-lwm2mpdm-sandbox.io 5684
[ FAILED ]	netcat lwm2mpdm-sandbox.io 443
[ FAILED ]	netcat tcp-lwm2mpdm-sandbox.io 443
[ FAILED ]	netcat edge-k8spdm-sandbox.io 443
[ FAILED ]	netcat gatewayspdm-sandbox.io 443
[ FAILED ]	netcat containerspdm-sandbox.io 443
fw-tools/edge-testnet: line 126: !LOG_FILE_NAME: unbound variable
```

diff --git a/.github/workflows/pr-checker.yml b/.github/workflows/pr-checker.yml
--- a/.github/workflows/pr-checker.yml
+++ b/.github/workflows/pr-checker.yml
@@ -69,6 +69,12 @@ jobs:
           echo "Failed to run edge-testnet -h"
           exit 1
         fi
+    - name: Check if it works with a custom domain
+      run: |
+        if ! fw-tools/edge-testnet --domain pdm-sandbox.io; then
+          echo "Failed to run edge-testnet -d example.com"
+          exit 1
+        fi
 
   versions-check:
     runs-on: [ "self-hosted", "client" ]
